using System.Windows;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Lumen.Core;
using Lumen.Infrastructure;
namespace Lumen.App;
public partial class App : System.Windows.Application
{
 private ServiceProvider? _services;
 protected override async void OnStartup(StartupEventArgs e){DpiAwareness.EnablePerMonitorV2();base.OnStartup(e);ShutdownMode=ShutdownMode.OnExplicitShutdown;var c=new ServiceCollection();c.AddLogging(b=>b.SetMinimumLevel(LogLevel.Information));c.AddSingleton<ISettingsService,JsonSettingsService>();c.AddSingleton<IApplicationStore,SqliteApplicationStore>();c.AddSingleton<IExecutableCandidateScorer,DefaultExecutableCandidateScorer>();c.AddSingleton<IShortcutResolver,WindowsShortcutResolver>();c.AddSingleton<IApplicationDiscoveryService,WindowsApplicationDiscoveryService>();c.AddSingleton<IMsixApplicationDiscoveryService,MsixApplicationDiscoveryService>();c.AddSingleton<IPortableScanner,PortableApplicationScanner>();c.AddSingleton<IResultExecutor,ResultExecutor>();c.AddSingleton<ISearchProvider,ApplicationSearchProvider>();c.AddSingleton<ISearchProvider,PortableApplicationSearchProvider>();c.AddSingleton<ISearchProvider,BuiltInCommandSearchProvider>();c.AddSingleton<SearchAggregator>();c.AddSingleton<IconCacheService>();c.AddSingleton<MainWindowViewModel>();c.AddSingleton<MainWindow>();c.AddSingleton<ILauncherWindowService>(p=>p.GetRequiredService<MainWindow>());c.AddSingleton<IGlobalHotkeyService,WpfGlobalHotkeyService>();c.AddSingleton<IndexRefreshService>();c.AddSingleton<TrayIconService>();c.AddTransient<SettingsWindow>();_services=c.BuildServiceProvider();try{await _services.GetRequiredService<ISettingsService>().LoadAsync();await _services.GetRequiredService<IApplicationStore>().InitializeAsync();await _services.GetRequiredService<IndexRefreshService>().RebuildStartupApplicationsAsync();}catch(Exception ex){_services.GetRequiredService<ILogger<App>>().LogError(ex,"Startup initialization failed");}var tray=_services.GetRequiredService<TrayIconService>();var window=_services.GetRequiredService<MainWindow>();var hotkey=_services.GetRequiredService<IGlobalHotkeyService>();hotkey.HotkeyPressed+=(_,_)=>window.ToggleLauncher();if(!hotkey.Register(_services.GetRequiredService<ISettingsService>().Current.Hotkey))tray.ShowWarning("快捷键不可用","默认快捷键已被其他程序占用；请在设置中更换。");window.ShowLauncher();_=_services.GetRequiredService<IndexRefreshService>().RebuildAsync();}
 protected override void OnExit(ExitEventArgs e){_services?.Dispose();base.OnExit(e);}
}
